### ISSUE TITLE
always ofline

### ISSUE THREAD

**Issue by ghost** [fuzzymannerz/MrMopDiscord#1]
the bot on my server is always offline for about 3 months know and not shore if its something to do with you guys doing something with it but I was just a heads up for you guys if you where not aware of it maybe offline in other servers

**Comment by fuzzymannerz** [comment]
There is no longer an official Mr. Mop bot due to lack of funding so the server closed down which is why I made it open source so people can host their own versions and tweak the code to their needs or whatever.
